# Generated by Django 5.0.6 on 2024-07-07 04:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroConsultorio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmpresa', models.CharField(max_length=50)),
                ('ruc', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('edad', models.IntegerField()),
                ('celular', models.CharField(max_length=15)),
                ('documento', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pagoDoctor', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ingresoClinica', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('gasto', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=1000, null=True)),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultorio')),
                ('dentista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultorio')),
                ('dentista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empleado')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento_Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empleado')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procedimiento')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol'),
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTransaccion', models.IntegerField()),
                ('fechaTransaccion', models.DateField()),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Procedimiento_Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.procedimiento')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento_Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convenio')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento_Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.transaccion')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tratamiento')),
            ],
        ),
    ]
