from django.urls import path
from .views import( PacienteListCreateView, PacienteRetrieveUpdateDestroyView,
                   EmpresaListCreateView, EmpresaRetrieveUpdateDestroyView,
    ConvenioListCreateView, ConvenioRetrieveUpdateDestroyView,
    ConsultorioListCreateView, ConsultorioRetrieveUpdateDestroyView,
    TratamientoListCreateView, TratamientoRetrieveUpdateDestroyView,
    TratamientoConvenioListCreateView, TratamientoConvenioRetrieveUpdateDestroyView,
    TransaccionListCreateView, TransaccionRetrieveUpdateDestroyView,
    TratamientoTransaccionListCreateView, TratamientoTransaccionRetrieveUpdateDestroyView,
    RolListCreateView, RolRetrieveUpdateDestroyView,
    EmpleadoListCreateView, EmpleadoRetrieveUpdateDestroyView,
    CitaListCreateView, CitaRetrieveUpdateDestroyView,
    ProcedimientoListCreateView, ProcedimientoRetrieveUpdateDestroyView,
    ProcedimientoTratamientoListCreateView, ProcedimientoTratamientoRetrieveUpdateDestroyView,
    ProcedimientoEmpleadoListCreateView, ProcedimientoEmpleadoRetrieveUpdateDestroyView
)

urlpatterns = [
    path('pacientes/', PacienteListCreateView.as_view(), name='paciente-list-create'),
    path('pacientes/<int:pk>/', PacienteRetrieveUpdateDestroyView.as_view(), name='paciente-detail'),
    path('empresas/', EmpresaListCreateView.as_view(), name='empresa-list-create'),
    path('empresas/<int:pk>/', EmpresaRetrieveUpdateDestroyView.as_view(), name='empresa-detail'),
    path('convenios/', ConvenioListCreateView.as_view(), name='convenio-list-create'),
    path('convenios/<int:pk>/', ConvenioRetrieveUpdateDestroyView.as_view(), name='convenio-detail'),
    path('consultorios/', ConsultorioListCreateView.as_view(), name='consultorio-list-create'),
    path('consultorios/<int:pk>/', ConsultorioRetrieveUpdateDestroyView.as_view(), name='consultorio-detail'),
    path('tratamientos/', TratamientoListCreateView.as_view(), name='tratamiento-list-create'),
    path('tratamientos/<int:pk>/', TratamientoRetrieveUpdateDestroyView.as_view(), name='tratamiento-detail'),
    path('tratamiento_convenios/', TratamientoConvenioListCreateView.as_view(), name='tratamiento-convenio-list-create'),
    path('tratamiento_convenios/<int:pk>/', TratamientoConvenioRetrieveUpdateDestroyView.as_view(), name='tratamiento-convenio-detail'),
    path('transacciones/', TransaccionListCreateView.as_view(), name='transaccion-list-create'),
    path('transacciones/<int:pk>/', TransaccionRetrieveUpdateDestroyView.as_view(), name='transaccion-detail'),
    path('tratamiento_transacciones/', TratamientoTransaccionListCreateView.as_view(), name='tratamiento-transaccion-list-create'),
    path('tratamiento_transacciones/<int:pk>/', TratamientoTransaccionRetrieveUpdateDestroyView.as_view(), name='tratamiento-transaccion-detail'),
    path('roles/', RolListCreateView.as_view(), name='rol-list-create'),
    path('roles/<int:pk>/', RolRetrieveUpdateDestroyView.as_view(), name='rol-detail'),
    path('empleados/', EmpleadoListCreateView.as_view(), name='empleado-list-create'),
    path('empleados/<int:pk>/', EmpleadoRetrieveUpdateDestroyView.as_view(), name='empleado-detail'),
    path('citas/', CitaListCreateView.as_view(), name='cita-list-create'),
    path('citas/<int:pk>/', CitaRetrieveUpdateDestroyView.as_view(), name='cita-detail'),
    path('procedimientos/', ProcedimientoListCreateView.as_view(), name='procedimiento-list-create'),
    path('procedimientos/<int:pk>/', ProcedimientoRetrieveUpdateDestroyView.as_view(), name='procedimiento-detail'),
    path('procedimiento_tratamientos/', ProcedimientoTratamientoListCreateView.as_view(), name='procedimiento-tratamiento-list-create'),
    path('procedimiento_tratamientos/<int:pk>/', ProcedimientoTratamientoRetrieveUpdateDestroyView.as_view(), name='procedimiento-tratamiento-detail'),
    path('procedimiento_empleados/', ProcedimientoEmpleadoListCreateView.as_view(), name='procedimiento-empleado-list-create'),
    path('procedimiento_empleados/<int:pk>/', ProcedimientoEmpleadoRetrieveUpdateDestroyView.as_view(), name='procedimiento-empleado-detail'),

]
